### ISSUE TITLE
PHP 7.1.0 segmentation fault

### ISSUE THREAD

**Issue by thekid** [xp-framework/core#148]
See for example [this build](https://travis-ci.org/xp-framework/core/jobs/128496755):

```sh
/home/travis/build.sh: line 45:  3104 Segmentation fault      (core dumped)
./xp -cp test.xar xp.unittest.Runner $i
```

**Comment by thekid** [comment]
Works on Windows with latest build:

```sh
$ XP_RT=master xp -e 'phpinfo()' | head -6
phpinfo()
PHP Version => 7.1.0-dev

System => Windows NT SLATE 10.0 build 10586 (Windows 10) i586
Build Date => May  7 2016 07:26:14
Compiler => MSVC14 (Visual C++ 2015)
```

**Comment by thekid** [comment]
Also works when I clone and compile PHP myself:

```sh
vagrant@vagrant-ubuntu-vivid-64:/devel/xp/core$ XP_RT=master xp -e 'phpinfo()' | head -5
phpinfo()
PHP Version => 7.1.0-dev

System => Linux vagrant-ubuntu-vivid-64 3.19.0-42-generic #48-Ubuntu SMP Thu Dec 17 22:54:45 UTC 2015 x86_64
Build Date => May  7 2016 12:21:47


vagrant@vagrant-ubuntu-vivid-64:/devel/xp/core$ XP_RT=master xp -cp test.xar xp.unittest.Runner src/test/conf ig/unittest/util.ini
# ...

♥: 884/889 run (5 skipped), 884 succeeded, 0 failed
Memory used: 6814.50 kB (11389.31 kB peak)
Time taken: 1.127 seconds
```

**Comment by thekid** [comment]
Running gdb on Travis-CI gave me the hint where to start searching: XDebug. I can now reproduce this locally:

```sh
$ /devel/php-src/sapi/cli/php -C -q -d include_path=.:/devel/xp/core::. \
  -d magic_quotes_gpc=0 \
  -d date.timezone=UTC \
  -d date.timezone=Europe/Berlin \
  -d zend_extension=/devel/xdebug/modules/xdebug.so \
  /usr/bin/class-main.php \
  xp.runtime.Version
Segmentation fault (core dumped)
```

**Comment by thekid** [comment]
..and GDB shows:

```sh
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff39da134 in xdebug_add_stack_frame (zdata=0x7ffff3c15db0, op_array=0x1163bc0 <zend_pass_function>, type=1)
    at /devel/xdebug/xdebug_stack.c:1387
1387                            tmp->lineno = cur_opcode->lineno;

(gdb) bt
#0  0x00007ffff39da134 in xdebug_add_stack_frame (zdata=0x7ffff3c15db0, op_array=0x1163bc0 <zend_pass_function>, type=1)
    at /devel/xdebug/xdebug_stack.c:1387
#1  0x00007ffff39b754f in xdebug_execute_internal (current_execute_data=0x7ffff3c15db0, return_value=0x7fffffffad30)
    at /devel/xdebug/xdebug.c:2008
#2  0x000000000095cc7f in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /devel/php-src/Zend/zend_vm_execute.h:993
#3  0x000000000095ff0c in ZEND_USER_OPCODE_SPEC_HANDLER () at /devel/php-src/Zend/zend_vm_execute.h:1783
#4  0x000000000095ad68 in execute_ex (ex=0x7ffff3c15ac0) at /devel/php-src/Zend/zend_vm_execute.h:425
#5  0x00007ffff39b6ddf in xdebug_execute_ex (execute_data=0x7ffff3c15ac0) at /devel/xdebug/xdebug.c:1893
#6  0x00000000009d21a5 in ZEND_INCLUDE_OR_EVAL_SPEC_TMPVAR_HANDLER () at /devel/php-src/Zend/zend_vm_execute.h:50243
#7  0x000000000095ff0c in ZEND_USER_OPCODE_SPEC_HANDLER () at /devel/php-src/Zend/zend_vm_execute.h:1783
#8  0x000000000095ad68 in execute_ex (ex=0x7ffff3c15960) at /devel/php-src/Zend/zend_vm_execute.h:425
#9  0x00007ffff39b6ddf in xdebug_execute_ex (execute_data=0x7ffff3c15960) at /devel/xdebug/xdebug.c:1893
#10 0x00000000009d21a5 in ZEND_INCLUDE_OR_EVAL_SPEC_TMPVAR_HANDLER () at /devel/php-src/Zend/zend_vm_execute.h:50243
#11 0x000000000095ff0c in ZEND_USER_OPCODE_SPEC_HANDLER () at /devel/php-src/Zend/zend_vm_execute.h:1783
#12 0x000000000095ad68 in execute_ex (ex=0x7ffff3c15030) at /devel/php-src/Zend/zend_vm_execute.h:425
#13 0x00007ffff39b6ddf in xdebug_execute_ex (execute_data=0x7ffff3c15030) at /devel/xdebug/xdebug.c:1893
#14 0x000000000095af6d in zend_execute (op_array=0x7ffff3c93000, return_value=0x0)
    at /devel/php-src/Zend/zend_vm_execute.h:470
#15 0x00000000008f1ff5 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /devel/php-src/Zend/zend.c:1427
#16 0x000000000082c1c1 in php_execute_script (primary_file=0x7fffffffd6c0) at /devel/php-src/main/main.c:2492
#17 0x00000000009e5c66 in do_cli (argc=15, argv=0x119f4d0) at /devel/php-src/sapi/cli/php_cli.c:982
#18 0x00000000009e70eb in main (argc=15, argv=0x119f4d0) at /devel/php-src/sapi/cli/php_cli.c:1352
```

**Comment by thekid** [comment]
Applying xdebug/xdebug#271 ("First batch of PHP 7.1 compatibility fixes") fixes the problem.

**Comment by thekid** [comment]
Removing XDebug makes tests succeed again, see this build: https://travis-ci.org/xp-framework/core/jobs/128512595
